services:
  - type: web
    name: nel-webapp
    env: node
    plan: free
    buildCommand: |
      npm install
      npx prisma generate
      npx prisma migrate deploy
      npm run set-super-admin
      npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: JWT_SECRET
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: nel-db
          property: connectionString

databases:
  - name: nel-db
    plan: free
    ipAllowList: [] 