import React, { createContext, useContext, useState, useEffect } from 'react';

// Define translations
const translations = {
  en: {
    settings: {
      profile: 'Profile',
      preferences: 'Preferences',
      theme: 'Theme',
      system: 'System',
      light: 'Light',
      dark: 'Dark',
      language: 'Language',
      chatColor: 'Chat Bubble Color',
      saveChanges: 'Save Changes',
      saving: 'Saving...',
      profileUpdated: 'Profile updated successfully',
      preferencesUpdated: 'Preferences updated successfully'
    },
    profile: {
      username: 'Username',
      displayName: 'Display Name',
      uploadPicture: 'Click to upload a new profile picture',
      enterUsername: 'Enter your username',
      enterDisplayName: 'Enter your display name',
      profilePicture: 'Profile Picture',
      changePassword: 'Change Password',
      currentPassword: 'Current Password',
      newPassword: 'New Password',
      confirmPassword: 'Confirm Password',
      passwordChanged: 'Password updated successfully',
      passwordMismatch: 'New passwords do not match',
      invalidCurrentPassword: 'Current password is incorrect'
    },
    chat: {
      sendMessage: 'Send message',
      typeMessage: 'Type your message...',
      loading: 'Loading messages...',
      noMessages: 'No messages yet. Start a conversation!',
      clearChat: 'Clear Chat',
      confirmClear: 'Are you sure you want to clear this conversation? This cannot be undone.',
      chatCleared: 'Chat history cleared successfully',
      noCharacterSelected: 'No character selected. Please select a character first.',
      messageTooLong: 'Message is too long. Please keep it under 2000 characters.',
      addReaction: 'Add reaction'
    },
    character: {
      new: 'New Character',
      edit: 'Edit Character',
      details: 'Character Details',
      public: {
        title: 'Make Public',
        description: 'Submit this character to the public explore page for others to use. Requires admin approval.',
        submit: 'Submit for Review',
        pending: 'Pending Review',
        approved: 'Approved',
        rejected: 'Rejected',
        private: 'Private'
      },
      personality: {
        title: 'Personality Configuration',
        traits: 'Personality',
        traitsPlaceholder: "Describe the character's core personality traits and behaviors...",
        traitsHelp: "Define the character's personality traits, mannerisms, and general behavior patterns.",
        backstory: 'Backstory',
        backstoryPlaceholder: "Write the character's background story and history...",
        backstoryHelp: "Provide background information that shapes the character's perspective and responses.",
        systemPrompt: 'System Prompt',
        systemPromptPlaceholder: 'Define the core personality and role of your character...',
        systemPromptHelp: "This is the initial system message that defines your character's core personality and behavior.",
        customInstructions: 'Custom Instructions',
        customInstructionsPlaceholder: 'Add any additional instructions or guidelines...',
        customInstructionsHelp: 'Additional instructions that will be appended to the system message to further customize behavior.',
        customInstructionsRequired: 'Custom instructions are required',
        tagsRequired: 'At least 3 tags are required (comma separated)',
        firstMessage: 'First Message',
        firstMessagePlaceholder: 'Enter the first message this character will send...',
        messageExample: 'Message Example',
        messageExamplePlaceholder: 'Enter an example message to show the character\'s style...',
        scenario: 'Scenario',
        scenarioPlaceholder: 'Describe a scenario or situation for this character...',
        creatorNotes: 'Creator Notes',
        creatorNotesPlaceholder: 'Add any notes or instructions for other users...',
        alternateGreetings: 'Alternate Greetings',
        alternateGreetingsPlaceholder: 'Enter alternate greeting messages (one per line)...'
      },
      fields: {
        name: 'Name',
        namePlaceholder: 'Character name',
        nameRequired: 'Name is required',
        age: 'Age',
        agePlaceholder: 'Age',
        gender: 'Gender',
        genderPlaceholder: 'Gender',
        race: 'Race',
        racePlaceholder: 'Race/Species',
        occupation: 'Occupation',
        occupationPlaceholder: "Character's role",
        likes: 'Likes',
        likesPlaceholder: 'Enter likes separated by commas (e.g., cats, reading, coffee)',
        dislikes: 'Dislikes',
        dislikesPlaceholder: 'Enter dislikes separated by commas (e.g., rain, loud noises, spiders)',
        avatar: 'Avatar URL or Upload',
        avatarPlaceholder: 'https://example.com/avatar.png',
        fullImage: 'Full-Body Image URL or Upload',
        fullImagePlaceholder: 'https://example.com/full.png',
        avatarRequired: 'Avatar is required',
        description: 'Description',
        descriptionPlaceholder: 'Describe your character...',
        systemPromptRequired: 'System prompt is required',
        missingFields: 'Please fill all required fields',
        personality: 'Personality',
        personalityPlaceholder: 'Describe the character\'s personality...',
        personalityRequired: 'Personality is required',
        descriptionRequired: 'Description is required',
        customInstructionsRequired: 'Custom instructions are required',
        tags: 'Tags (comma separated)',
        tagsPlaceholder: 'tag1, tag2, tag3',
        tagsRequired: 'At least 3 tags are required (comma separated)'
      },
      actions: {
        resetDefaults: 'Reset to Defaults',
        upload: 'Upload',
        save: 'Save',
        cancel: 'Cancel'
      },
      metadata: {
        yearsOld: 'years old'
      },
      delete: 'Delete Character',
      deleted: 'Character deleted.',
      deleteFailed: 'Failed to delete character.',
      confirmDelete: 'Are you sure you want to delete this character? This cannot be undone.',
      confirmCreate: 'Confirm Character Creation',
      confirmCreateDesc: 'Are you sure you want to create this character?',
      confirmCreatePublic: 'Submit Public Character',
      confirmCreatePublicDesc: 'This character will be submitted for public review and, if approved, will be visible to all users.',
      reviewError: 'Character created but failed to submit for review. You can try submitting it later.',
      created: 'Character created!',
      createError: 'Failed to create character',
      createFailed: 'Failed to create character',
      submittedForApproval: 'Character submitted for approval!',
      addedToPrivate: 'Character added to private collection!',
      customInstructionsRequired: 'Custom instructions are required',
      tagsRequired: 'At least 3 tags are required (comma separated)'
    },
    sidebar: {
      characters: 'Characters',
      settings: 'Settings',
      newCharacter: 'New Character',
      search: 'Search characters...'
    },
    common: {
      actions: {
        create: 'Create',
        delete: 'Delete',
        cancel: 'Cancel',
        save: 'Save',
        edit: 'Edit',
        refresh: 'Refresh Page',
        goHome: 'Go to Home',
        logout: 'Logout',
        confirm: 'Confirm',
        back: 'Back',
        next: 'Next',
        previous: 'Previous',
        close: 'Close',
        open: 'Open',
        search: 'Search',
        filter: 'Filter',
        sort: 'Sort',
        view: 'View',
        hide: 'Hide',
        show: 'Show',
        more: 'More',
        less: 'Less',
        all: 'All',
        none: 'None',
        select: 'Select',
        deselect: 'Deselect',
        upload: 'Upload',
        download: 'Download',
        remove: 'Remove',
        add: 'Add',
        update: 'Update',
        submit: 'Submit',
        reset: 'Reset',
        clear: 'Clear'
      },
      status: {
        required: 'Required',
        optional: 'Optional',
        success: 'Success',
        warning: 'Warning',
        info: 'Information',
        error: 'Error',
        help: 'Help'
      },
      roles: {
        admin: 'Admin',
        moderator: 'Moderator',
        user: 'User',
        guest: 'Guest'
      },
      states: {
        online: 'Online',
        offline: 'Offline',
        active: 'Active',
        inactive: 'Inactive',
        pending: 'Pending',
        approved: 'Approved',
        rejected: 'Rejected',
        blocked: 'Blocked',
        unblocked: 'Unblocked',
        enabled: 'Enabled',
        disabled: 'Disabled',
        public: 'Public',
        private: 'Private',
        visible: 'Visible',
        hidden: 'Hidden',
        default: 'Default',
        custom: 'Custom',
        system: 'System',
        manual: 'Manual',
        automatic: 'Automatic',
        yes: 'Yes',
        no: 'No',
        true: 'True',
        false: 'False',
        on: 'On',
        off: 'Off',
        connected: 'Connected',
        disconnected: 'Disconnected',
        available: 'Available',
        unavailable: 'Unavailable',
        busy: 'Busy',
        idle: 'Idle',
        away: 'Away'
      },
      sections: {
        settings: 'Settings',
        preferences: 'Preferences',
        profile: 'Profile',
        account: 'Account',
        security: 'Security',
        privacy: 'Privacy',
        notifications: 'Notifications',
        messages: 'Messages',
        characters: 'Characters',
        users: 'Users'
      },
      loading: 'Loading...',
      error: 'Something went wrong'
    }
  },
  es: {
    settings: {
      profile: 'Perfil',
      preferences: 'Preferencias',
      theme: 'Tema',
      system: 'Sistema',
      light: 'Claro',
      dark: 'Oscuro',
      language: 'Idioma',
      chatColor: 'Color de Burbuja de Chat',
      saveChanges: 'Guardar Cambios',
      saving: 'Guardando...',
      profileUpdated: 'Perfil actualizado exitosamente',
      preferencesUpdated: 'Preferencias actualizadas exitosamente'
    },
    profile: {
      username: 'Nombre de Usuario',
      displayName: 'Nombre para Mostrar',
      uploadPicture: 'Haz clic para subir una nueva foto de perfil',
      enterUsername: 'Ingresa tu nombre de usuario',
      enterDisplayName: 'Ingresa tu nombre para mostrar',
      profilePicture: 'Foto de Perfil',
      changePassword: 'Cambiar Contraseña',
      currentPassword: 'Contraseña Actual',
      newPassword: 'Nueva Contraseña',
      confirmPassword: 'Confirmar Contraseña',
      passwordChanged: 'Contraseña actualizada exitosamente',
      passwordMismatch: 'Las nuevas contraseñas no coinciden',
      invalidCurrentPassword: 'La contraseña actual es incorrecta'
    },
    chat: {
      sendMessage: 'Enviar mensaje',
      typeMessage: 'Escribe tu mensaje...',
      loading: 'Cargando mensajes...',
      noMessages: '¡No hay mensajes aún. ¡Inicia una conversación!',
      clearChat: 'Limpiar chat',
      confirmClear: '¿Estás seguro de que quieres borrar esta conversación? Esta acción no se puede deshacer.',
      chatCleared: 'Historial de chat borrado exitosamente',
      noCharacterSelected: 'No hay personaje seleccionado. Por favor, selecciona un personaje primero.',
      messageTooLong: 'El mensaje es demasiado largo. Por favor, mantenlo por debajo de 2000 caracteres.',
      addReaction: 'Añadir reacción'
    },
    character: {
      new: 'Nuevo Personaje',
      edit: 'Editar Personaje',
      details: 'Detalles del Personaje',
      public: {
        title: 'Hacer Público',
        description: 'Enviar este personaje a la página de exploración pública para que otros lo utilicen. Requiere aprobación del administrador.',
        submit: 'Enviar para Revisión',
        pending: 'Pendiente de Revisión',
        approved: 'Aprobado',
        rejected: 'Rechazado',
        private: 'Privado'
      },
      personality: {
        title: 'Configuración de Personalidad',
        traits: 'Personalidad',
        traitsPlaceholder: "Describe los rasgos de personalidad y comportamientos principales del personaje...",
        traitsHelp: "Define los rasgos de personalidad, manierismos y patrones generales de comportamiento del personaje.",
        backstory: 'Historia',
        backstoryPlaceholder: "Escribe la historia y antecedentes del personaje...",
        backstoryHelp: "Proporciona información de fondo que da forma a la perspectiva y respuestas del personaje.",
        systemPrompt: 'Prompt del Sistema',
        systemPromptPlaceholder: 'Define la personalidad y el rol principal de tu personaje...',
        systemPromptHelp: "Este es el mensaje inicial del sistema que define la personalidad y el comportamiento principal de tu personaje.",
        customInstructions: 'Instrucciones Personalizadas',
        customInstructionsPlaceholder: 'Agrega instrucciones o pautas adicionales...',
        customInstructionsHelp: 'Instrucciones adicionales que se agregarán al mensaje del sistema para personalizar aún más el comportamiento.',
        customInstructionsRequired: 'Las instrucciones personalizadas son obligatorias',
        tagsRequired: 'Se requieren al menos 3 etiquetas (separadas por comas)',
        firstMessage: 'Primer Mensaje',
        firstMessagePlaceholder: 'Ingresa el primer mensaje que enviará este personaje...',
        messageExample: 'Ejemplo de Mensaje',
        messageExamplePlaceholder: 'Ingresa un mensaje de ejemplo para mostrar el estilo del personaje...',
        scenario: 'Escenario',
        scenarioPlaceholder: 'Describe un escenario o situación para este personaje...',
        creatorNotes: 'Notas del Creador',
        creatorNotesPlaceholder: 'Agrega notas o instrucciones para otros usuarios...',
        alternateGreetings: 'Saludos Alternativos',
        alternateGreetingsPlaceholder: 'Ingresa mensajes de saludo alternativos (uno por línea)...'
      },
      fields: {
        name: 'Nombre',
        namePlaceholder: 'Nombre del personaje',
        nameRequired: 'El nombre es obligatorio',
        age: 'Edad',
        agePlaceholder: 'Edad',
        gender: 'Género',
        genderPlaceholder: 'Género',
        race: 'Raza',
        racePlaceholder: 'Raza/Especie',
        occupation: 'Ocupación',
        occupationPlaceholder: "Rol del personaje",
        likes: 'Gustos',
        likesPlaceholder: 'Ingresa gustos separados por comas (ej: gatos, lectura, café)',
        dislikes: 'Disgustos',
        dislikesPlaceholder: 'Ingresa disgustos separados por comas (ej: lluvia, ruidos fuertes, arañas)',
        avatar: 'URL de Avatar o Subir',
        avatarPlaceholder: 'https://ejemplo.com/avatar.png',
        fullImage: 'URL de Imagen Completa o Subir',
        fullImagePlaceholder: 'https://ejemplo.com/completa.png',
        avatarRequired: 'El avatar es obligatorio',
        description: 'Descripción',
        descriptionPlaceholder: 'Describe tu personaje...',
        systemPromptRequired: 'El prompt del sistema es obligatorio',
        missingFields: 'Please fill all required fields',
        personality: 'Personalidad',
        personalityPlaceholder: 'Describe la personalidad del personaje...',
        personalityRequired: 'La personalidad es obligatoria',
        descriptionRequired: 'La descripción es obligatoria',
        customInstructionsRequired: 'Las instrucciones personalizadas son obligatorias',
        tags: 'Etiquetas (separadas por comas)',
        tagsPlaceholder: 'etiqueta1, etiqueta2, etiqueta3',
        tagsRequired: 'Se requieren al menos 3 etiquetas (separadas por comas)'
      },
      actions: {
        resetDefaults: 'Restablecer Valores',
        upload: 'Subir',
        save: 'Guardar',
        cancel: 'Cancelar'
      },
      metadata: {
        yearsOld: 'años'
      },
      delete: 'Eliminar personaje',
      deleted: 'Personaje eliminado.',
      deleteFailed: 'No se pudo eliminar el personaje.',
      confirmDelete: '¿Estás seguro de que deseas eliminar este personaje? Esto no se puede deshacer.',
      confirmCreate: 'Confirmar creación de personaje',
      confirmCreateDesc: '¿Estás seguro de que deseas crear este personaje?',
      confirmCreatePublic: 'Enviar personaje público',
      confirmCreatePublicDesc: 'Este personaje será enviado para revisión pública y, si es aprobado, será visible para todos los usuarios.',
      reviewError: 'Personaje creado pero no se pudo enviar para revisión. Puedes intentar enviarlo más tarde.',
      created: '¡Personaje creado!',
      createError: 'No se pudo crear el personaje',
      createFailed: 'No se pudo crear el personaje',
      submittedForApproval: '¡Personaje enviado para aprobación!',
      addedToPrivate: '¡Personaje añadido a la colección privada!',
      customInstructionsRequired: 'Las instrucciones personalizadas son obligatorias',
      tagsRequired: 'Se requieren al menos 3 etiquetas (separadas por comas)'
    },
    sidebar: {
      characters: 'Personajes',
      settings: 'Configuración',
      newCharacter: 'Nuevo personaje',
      search: 'Buscar personajes...'
    },
    common: {
      create: 'Crear',
      delete: 'Eliminar',
      cancel: 'Cancelar',
      save: 'Guardar',
      edit: 'Editar',
      loading: 'Cargando...',
      error: 'Algo salió mal',
      refresh: 'Actualizar Página',
      goHome: 'Ir al Inicio',
      logout: 'Cerrar Sesión',
      confirm: 'Confirmar',
      back: 'Atrás',
      next: 'Siguiente',
      previous: 'Anterior',
      close: 'Cerrar',
      open: 'Abrir',
      search: 'Buscar',
      filter: 'Filtrar',
      sort: 'Ordenar',
      view: 'Ver',
      hide: 'Ocultar',
      show: 'Mostrar',
      more: 'Más',
      less: 'Menos',
      all: 'Todos',
      none: 'Ninguno',
      select: 'Seleccionar',
      deselect: 'Deseleccionar',
      upload: 'Subir',
      download: 'Descargar',
      remove: 'Eliminar',
      add: 'Añadir',
      update: 'Actualizar',
      submit: 'Enviar',
      reset: 'Restablecer',
      clear: 'Limpiar',
      required: 'Obligatorio',
      optional: 'Opcional',
      success: 'Éxito',
      warning: 'Advertencia',
      info: 'Información',
      error: 'Error',
      help: 'Ayuda',
      settings: 'Configuración',
      preferences: 'Preferencias',
      profile: 'Perfil',
      account: 'Cuenta',
      security: 'Seguridad',
      privacy: 'Privacidad',
      notifications: 'Notificaciones',
      messages: 'Mensajes',
      characters: 'Personajes',
      users: 'Usuarios',
      admin: 'Administrador',
      moderator: 'Moderador',
      user: 'Usuario',
      guest: 'Invitado',
      online: 'En línea',
      offline: 'Desconectado',
      active: 'Activo',
      inactive: 'Inactivo',
      pending: 'Pendiente',
      approved: 'Aprobado',
      rejected: 'Rechazado',
      blocked: 'Bloqueado',
      unblocked: 'Desbloqueado',
      enabled: 'Habilitado',
      disabled: 'Deshabilitado',
      public: 'Público',
      private: 'Privado',
      visible: 'Visible',
      hidden: 'Oculto',
      default: 'Predeterminado',
      custom: 'Personalizado',
      system: 'Sistema',
      manual: 'Manual',
      automatic: 'Automático',
      yes: 'Sí',
      no: 'No',
      true: 'Verdadero',
      false: 'Falso',
      on: 'Activado',
      off: 'Desactivado',
      enabled: 'Habilitado',
      disabled: 'Deshabilitado',
      active: 'Activo',
      inactive: 'Inactivo',
      connected: 'Conectado',
      disconnected: 'Desconectado',
      available: 'Disponible',
      unavailable: 'No disponible',
      busy: 'Ocupado',
      idle: 'Inactivo',
      away: 'Ausente',
      online: 'En línea',
      offline: 'Desconectado',
      status: 'Estado',
      state: 'Estado',
      condition: 'Condición',
      mode: 'Modo',
      type: 'Tipo',
      category: 'Categoría',
      group: 'Grupo',
      role: 'Rol',
      permission: 'Permiso',
      access: 'Acceso',
      level: 'Nivel',
      priority: 'Prioridad',
      importance: 'Importancia',
      severity: 'Severidad',
      impact: 'Impacto',
      scope: 'Alcance',
      range: 'Rango',
      limit: 'Límite',
      threshold: 'Umbral',
      boundary: 'Límite',
      constraint: 'Restricción',
      restriction: 'Restricción',
      requirement: 'Requisito',
      condition: 'Condición',
      rule: 'Regla',
      policy: 'Política',
      guideline: 'Directriz',
      standard: 'Estándar',
      protocol: 'Protocolo',
      procedure: 'Procedimiento',
      process: 'Proceso',
      workflow: 'Flujo de trabajo',
      pipeline: 'Canalización',
      queue: 'Cola',
      stack: 'Pila',
      heap: 'Montón',
      cache: 'Caché',
      buffer: 'Búfer',
      pool: 'Grupo',
      thread: 'Hilo',
      process: 'Proceso',
      task: 'Tarea',
      job: 'Trabajo',
      service: 'Servicio',
      application: 'Aplicación',
      system: 'Sistema',
      platform: 'Plataforma',
      environment: 'Entorno',
      context: 'Contexto',
      scope: 'Alcance',
      namespace: 'Espacio de nombres',
      domain: 'Dominio',
      region: 'Región',
      zone: 'Zona',
      area: 'Área',
      section: 'Sección',
      part: 'Parte',
      component: 'Componente',
      module: 'Módulo',
      package: 'Paquete',
      library: 'Biblioteca',
      framework: 'Framework',
      tool: 'Herramienta',
      utility: 'Utilidad',
      helper: 'Ayudante',
      service: 'Servicio',
      provider: 'Proveedor',
      client: 'Cliente',
      server: 'Servidor',
      host: 'Host',
      node: 'Nodo',
      endpoint: 'Punto final',
      interface: 'Interfaz',
      api: 'API',
      sdk: 'SDK',
      cli: 'CLI',
      gui: 'GUI',
      ui: 'UI',
      ux: 'UX',
      db: 'Base de datos'
    },
    errors: {
      required: 'Este campo es obligatorio',
      invalidEmail: 'Correo electrónico inválido',
      passwordMismatch: 'Las contraseñas no coinciden',
      invalidCredentials: 'Correo o contraseña inválidos',
      serverError: 'Ocurrió un error en el servidor',
      unexpectedError: 'Lo sentimos, pero algo inesperado sucedió. Por favor, intenta refrescar la página.',
      networkError: 'Error de red. Por favor, verifica tu conexión.',
      timeoutError: 'La solicitud ha expirado. Por favor, inténtalo de nuevo.',
      validationError: 'Error de validación.',
      authorizationError: 'No estás autorizado para realizar esta acción.',
      authenticationError: 'Error de autenticación. Por favor, inicia sesión nuevamente.',
      permissionError: 'No tienes permiso para realizar esta acción.',
      notFoundError: 'No se encontró el recurso solicitado.',
      conflictError: 'Ocurrió un conflicto al procesar tu solicitud.',
      rateLimitError: 'Demasiadas solicitudes. Por favor, inténtalo más tarde.',
      maintenanceError: 'El sistema está en mantenimiento. Por favor, inténtalo más tarde.',
      serviceUnavailableError: 'El servicio no está disponible. Por favor, inténtalo más tarde.',
      badRequestError: 'Solicitud inválida. Por favor, verifica tu entrada.',
      forbiddenError: 'Acceso prohibido.',
      methodNotAllowedError: 'Método no permitido.',
      notAcceptableError: 'No aceptable.',
      proxyAuthenticationRequiredError: 'Se requiere autenticación de proxy.',
      requestTimeoutError: 'Tiempo de espera de la solicitud agotado.',
      lengthRequiredError: 'Se requiere longitud.',
      preconditionFailedError: 'Error de precondición.',
      payloadTooLargeError: 'Carga útil demasiado grande.',
      uriTooLongError: 'URI demasiado larga.',
      unsupportedMediaTypeError: 'Tipo de medio no soportado.',
      rangeNotSatisfiableError: 'Rango no satisfacible.',
      expectationFailedError: 'Error de expectativa.',
      imATeapotError: 'Soy una tetera.',
      misdirectedRequestError: 'Solicitud mal dirigida.',
      unprocessableEntityError: 'Entidad no procesable.',
      lockedError: 'Bloqueado.',
      failedDependencyError: 'Dependencia fallida.',
      tooEarlyError: 'Demasiado temprano.',
      upgradeRequiredError: 'Se requiere actualización.',
      preconditionRequiredError: 'Se requiere precondición.',
      tooManyRequestsError: 'Demasiadas solicitudes.',
      requestHeaderFieldsTooLargeError: 'Campos de encabezado de solicitud demasiado grandes.',
      unavailableForLegalReasonsError: 'No disponible por razones legales.',
      internalServerError: 'Error interno del servidor.',
      notImplementedError: 'No implementado.',
      badGatewayError: 'Puerta de enlace incorrecta.',
      serviceUnavailableError: 'Servicio no disponible.',
      gatewayTimeoutError: 'Tiempo de espera de la puerta de enlace agotado.',
      httpVersionNotSupportedError: 'Versión HTTP no soportada.',
      variantAlsoNegotiatesError: 'La variante también negocia.',
      insufficientStorageError: 'Almacenamiento insuficiente.',
      loopDetectedError: 'Bucle detectado.',
      notExtendedError: 'No extendido.',
      networkAuthenticationRequiredError: 'Se requiere autenticación de red.'
    },
    admin: {
      title: 'Panel de administración',
      searchUsers: 'Buscar usuarios...',
      backToHome: 'Volver al inicio',
      systemOverview: 'Resumen del sistema',
      users: 'Usuarios',
      messages: 'Mensajes',
      characters: 'Personajes',
      stats: 'Estadísticas',
      recentActivity: 'Actividad reciente',
      role: 'Rol',
      status: 'Estado',
      joined: 'Registrado',
      lastLogin: 'Último acceso',
      totalMessages: 'Mensajes totales',
      charactersCreated: 'Personajes creados',
      activeSessions: 'Sesiones activas',
      blocked: 'Bloqueado',
      online: 'En línea',
      offline: 'Desconectado',
      resetPassword: 'Restablecer contraseña',
      blockUser: 'Bloquear usuario',
      unblockUser: 'Desbloquear usuario',
      deleteUser: 'Eliminar usuario',
      activityStats: 'Estadísticas de actividad',
      basicInfo: 'Información básica',
      activity: 'Actividad',
      systemStats: 'Estadísticas del sistema',
      createdToday: 'Creado hoy',
      avgPerUser: 'Prom. por usuario',
      newToday: 'Nuevo hoy',
      activeNow: 'Activos ahora',
      avgMessagesPerUser: 'Prom. por usuario',
      systemActivity: 'Actividad reciente del sistema',
      removeDuplicatesAll: 'Eliminar personajes Nelliel duplicados (Todos)',
      removeDuplicatesUser: 'Eliminar personajes Nelliel duplicados (Usuario)',
      duplicatesRemoved: 'Se eliminaron %{count} personajes Nelliel duplicados.',
      noDuplicatesFound: 'No se encontraron personajes Nelliel duplicados.',
      duplicateCleanupFailed: 'No se pudo limpiar duplicados: %{error}',
      SUPER_ADMIN: 'Super Admin',
      USER: 'Usuario',
      MODERATOR: 'Moderador',
      ADMIN: 'Administrador'
    },
    explore: {
      title: 'Explore Characters',
      subtitle: 'Discover and add new characters created by the community!',
      description: 'Discover and add new characters created by the community!',
      create: 'Create Public Character',
      add: 'Add to My Characters',
      added: 'Added to My Characters',
      pending: 'Pending Review',
      approved: 'Approved',
      rejected: 'Rejected',
      private: 'Private',
      search: 'Search characters...',
      filter: 'Filter by tags...',
      noResults: 'No characters found',
      loading: 'Loading characters...',
      error: 'Error loading characters',
      submitSuccess: 'Character submitted for review',
      submitError: 'Error submitting character',
      addSuccess: 'Character added to your collection',
      addError: 'Error adding character to collection',
      back: 'Back to Chat',
      view: 'View',
    },
    notifications: {
      title: 'Notificaciones',
      loading: 'Cargando notificaciones...',
      empty: 'No hay notificaciones',
      markAsRead: 'Marcar como leída',
      markAllRead: 'Marcar todas como leídas',
      delete: 'Eliminar',
      deleted: 'Notificación eliminada',
      fetchError: 'Error al cargar notificaciones',
      markReadError: 'Error al marcar notificación como leída',
      markAllReadError: 'Error al marcar todas las notificaciones como leídas',
      deleteError: 'Error al eliminar notificación',
      allRead: 'Todas las notificaciones marcadas como leídas',
      characterSubmitted: {
        title: 'Personaje Enviado',
        message: 'Tu personaje ha sido enviado para revisión pública. Cualquier cambio realizado en tu copia privada no afectará a la versión enviada. Serás notificado cuando sea aprobado o rechazado.'
      },
      characterApproved: {
        title: 'Personaje Aprobado',
        message: '¡Tu personaje ha sido aprobado y ahora es público!'
      },
      characterRejected: {
        title: 'Personaje Rechazado',
        message: 'Tu personaje ha sido rechazado. Razón: %{reason}'
      },
      deleteAll: 'Eliminar todas las notificaciones',
      allDeleted: 'Todas las notificaciones eliminadas'
    }
  }
};

const LanguageContext = createContext();

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('language');
    return saved || 'en';
  });

  // Update language in localStorage when it changes
  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key) => {
    const keys = key.split('.');
    let value = translations[language];
    for (const k of keys) {
      value = value?.[k];
    }
    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
} 